import manifest from '@/data/page-sources.generated.json'

// Per-page "Sources" section, driven by the network claims ledger.
// The manifest is generated by docs/claims/gen-sources.mjs — do not hand-edit it.
// Renders nothing for routes with no ledger-verified claims.

type SourceClaim = { id: string; claim: string; status: string; sources: string[] }

const ROUTES = (manifest.routes ?? {}) as Record<string, SourceClaim[]>
const SITE_ORIGIN = 'https://dayonecitizen.com'

function sourceLabel(url: string): string {
  try {
    const u = new URL(url)
    if (u.hostname.startsWith('support.')) return 'RSI Support'
    if (u.hostname.includes('gamespress')) return 'CIG Press Release'
    if (u.hostname.includes('robertsspaceindustries')) {
      if (u.pathname.includes('/comm-link/')) return 'RSI Comm-Link'
      if (u.pathname.includes('referral-program')) return 'RSI Referral Program'
      if (u.pathname.includes('funding')) return 'RSI Funding Tracker'
      if (u.pathname.includes('squadron42')) return 'RSI — Squadron 42'
      return 'RSI Official'
    }
    return u.hostname.replace(/^www\./, '')
  } catch {
    return 'Source'
  }
}

export default function PageSources({ route }: { route: string }) {
  const claims = ROUTES[route]
  if (!claims || claims.length === 0) return null

  const canonical = route === '/' ? `${SITE_ORIGIN}/` : `${SITE_ORIGIN}${route}`
  const citationUrls = [...new Set(claims.flatMap((c) => c.sources))]
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    '@id': canonical,
    url: canonical,
    citation: citationUrls.map((url) => ({ '@type': 'CreativeWork', url })),
  }

  return (
    <section className="border-t border-white/5 bg-navy py-16" aria-labelledby="page-sources-heading">
      <div className="container-narrow">
        <div className="mx-auto max-w-3xl">
          <p className="mb-3 text-xs font-semibold uppercase tracking-[0.2em] text-gold">
            Sources
          </p>
          <h2 id="page-sources-heading" className="heading-display text-2xl sm:text-3xl">
            Where these facts come from
          </h2>
          <p className="mt-4 text-sm text-muted">
            Every factual claim on this page is checked against official Cloud
            Imperium Games sources. Dates and figures are verified against the
            primary RSI blog post or support article linked below — not
            third-party trackers.
          </p>
          <ul className="mt-8 space-y-4">
            {claims.map((c) => (
              <li key={c.id} className="card-surface p-5">
                <p className="text-sm text-starwhite/90">{c.claim}</p>
                <div className="mt-3 flex flex-wrap gap-x-4 gap-y-1">
                  {c.sources.map((url) => (
                    <a
                      key={url}
                      href={url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="font-mono text-xs text-gold underline-offset-4 hover:underline"
                    >
                      {sourceLabel(url)} ↗
                    </a>
                  ))}
                </div>
              </li>
            ))}
          </ul>
        </div>
      </div>

      <script
        type="application/ld+json"
        // eslint-disable-next-line react/no-danger
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
    </section>
  )
}
